platform :ios, "8.0"

source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/magnetsystems/Specs'

use_frameworks!

pod 'MagnetMax', '~> 2.4'
pod 'JSQMessagesViewController'
pod 'NYTPhotoViewer', '~> 1.0.0'
pod 'DZVideoPlayerViewController'
pod 'Toucan'
