source 'https://github.com/CocoaPods/Specs.git'
# Use Magnet’s internal repo
source 'https://github.com/magnetsystems/iOS-Distribution.git'

platform :ios, '8.0'
use_frameworks!

pod 'MagnetMax', '~> 2.0'

post_install do |installer|
 `find Pods -regex 'Pods\\/Mantle\\/Mantle\\/Mantle\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)Mantle\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
end