source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/magnetsystems/Specs.git'
platform :ios, '8.0'

use_frameworks!

target 'RichMessaging' do

pod 'MagnetMax', '~> 2.0'
pod 'JSQMessagesViewController', :git => 'https://github.com/jessesquires/JSQMessagesViewController.git', :branch => 'develop'
pod 'FBSDKLoginKit'

pod 'AFAmazonS3Manager', '~> 3.2', :inhibit_warnings => true

end

target 'RichMessagingTests' do

end

