source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'MMX', :git => 'https://github.com/magnetsystems/message-ios.git', :branch => 'friends_of_magnet'
pod 'SlackTextViewController', '1.5.2', :inhibit_warnings => true