source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/magnetsystems/Specs.git'
source 'https://github.com/magnetsystems/iOS-Distribution.git'

platform :ios, '8.0'
use_frameworks!

pod 'MagnetMax', '~> 2.3'
pod 'MBProgressHUD'