source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/magnetsystems/iOS-Distribution'
source 'https://github.com/magnetsystems/Specs.git'

inhibit_all_warnings!

  use_frameworks!
  pod 'ChatKit', :path => '../../'


